---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 2-demo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./2-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  resources:
    - namespace.yml
    - deployment.yml
    - service.yml
