---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 2-demo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./1-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
